################################# Default configuration ###################
baseURL = "Yaltopia Entertainment"
title = "Yaltopia Entertainment"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
page = ""
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
page = ""
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
page = "/"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
page = "/"
attributes = ""

[[params.plugins.css]]
link = "plugins/themefisher-font/style.css"
page = "video/"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
page = "contact/"
attributes = ""





############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/YGTrans2.png"
logo_width = "150px"
# Meta data
description = "This is meta description"
author = "Yaltopia"
# Contact Information
mobile = "+251-983032475"
email = "YaltopiaEnteritament@gmail.com"
location = "Addis Ababa, Ethiopia"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
icon = "ion-social-youtube-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.youtube.com/channel/UCUbhCDAPBhUBweSzNMohOmw"

[[params.social]]
icon = "ion-paper-airplane" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://t.me/YaltopyaET"

[[params.social]]
icon = "ion-social-freebsd-devil" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://discord.gg/6gCVmnM2TB"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/yaltopyatech/"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/yaltopyatech"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/Yaltopya-Entertainment-112253630512020"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 Yaltopia Enteritament All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1


[[Languages.en.menu.main]]
name = "Video"
URL = "video"
weight = 2

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.en.menu.main]]
name = "Service"
URL = "service"
weight = 6

[[Languages.en.menu.main]]
name = "Tournament"
URL = "https://www.toornament.com/en_US/tournaments/4121204366826291200/registration/"
weight = 4  

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 6


[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 7


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 8

[[Languages.en.menu.footer]]
name = "Video"
URL = "video"
weight = 2

[[Languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3


[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Copyright ; 2020 Yaltopia Tech All Rights Reserved"


######################### france navigation #############################
# main menu
[[Languages.fr.menu.main]]
name = "Accueil"
URL = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "À propos"
URL = "about"
weight = 2

[[Languages.fr.menu.main]]
name = "Projet"
URL = "project"
weight = 3

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.fr.menu.main]]
weight = 5
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Tarification"
  URL = "pricing"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Un service"
  URL = "service"
  
[[Languages.fr.menu.main]]
name = "contact"
URL = "contact"
weight = 6


# footer menu
[[Languages.fr.menu.footer]]
name = "about"
URL = "about"
weight = 1

[[Languages.fr.menu.footer]]
name = "project"
URL = "project"
weight = 2

[[Languages.fr.menu.footer]]
name = "service"
URL = "service"
weight = 3

[[Languages.fr.menu.footer]]
name = "pricing"
URL = "pricing"
weight = 4

[[Languages.fr.menu.footer]]
name = "faq"
URL = "faq"
weight = 5

[[Languages.fr.menu.footer]]
name = "contact"
URL = "contact"
weight = 6
